### ISSUE TITLE
BRO, Please help me to use it))) What command should i put in SHELL window for running my search and to enjoy your brilliant script/ i m novice in python//// Grate thanks to you 

### ISSUE THREAD

**Issue by Isocteur** [felipetdsa/Bitcoin---Is-wallet-used---Ver.-2.0#1]
BRO, Please help me to use it))) What command should i put in SHELL window for running my search and to enjoy your brilliant script/ i m novice in python//// Grate thanks to you

**Comment by felipetdsa** [comment]
Exemple:
pp2("1JxQYvpxXVq5Xiotpq2jwsEgdJQynH5uJH", 100, 5)

It will search for 5 pages starting at 100th page.

Will return a list with page and line of the direct.io with the wallet.

**Comment by Isocteur** [comment]
Thanks a lot i will try it))))

**Comment by Isocteur** [comment]
so one more question if i want to use the list of wallets (several wallets) how should i input it? i mean separate by comma or by space or through semicolon.
Grate Thanks!
